  
    const playerImages = [
        { name: "L. Messi", image: "/L. Messi.png" },
        { name: "Cristiano Ronaldo", image: "/Cristiano Ronaldo.png" },
        { name: "Neymar Jr", image: "/Neymar Jr.png" },
        { name: "L. Modrić", image: "/L. Modrić.png" },
        { name: "K. De Bruyne", image: "/K. De Bruyne.png" },
        { name: "E. Hazard", image: "/E. Hazard.png" },
        { name: "S. Ramos", image: "/S. Ramos.png" },
        { name: "L. Suárez", image: "/L. Suárez.png" },
        { name: "D. De Gea", image: "/D. De Gea.png" },
        { name: "R. Lewandowski", image: "/R. Lewandowski.png" },
        { name: "M. Neuer", image: "/M. Neuer.png" },
        { name: "J. Oblak", image: "/J. Oblak.png" },
        { name: "T. Courtois", image: "/T. Courtois.png" },
        { name: "D. Godín", image: "/D. Godín.png" },
        { name: "T. Kroos", image: "/T. Kroos.png" },
        { name: "A. Griezmann", image: "/A. Griezmann.png" },
        { name: "N. Kanté", image: "/N. Kanté.png" },
        { name: "P. Dybala", image: "/P. Dybala.png" },
        { name: "H. Kane", image: "/H. Kane.png" },
        { name: "G. Chiellini", image: "/G. Chiellini.png" },
        { name: "S. Agüero", image: "/S. Agüero.png" },
        { name: "K. Mbappé", image: "/K. Mbappé.png" },
        { name: "M. Salah", image: "/M. Salah.png" },
        { name: "Casemiro", image: "/Casemiro.png" },
        { name: "Marcelo", image: "/Marcelo.png" },
        { name: "Isco", image: "/Isco.png" },
        { name: "E. Cavani", image: "/E. Cavani.png" },
        { name: "M. Hummels", image: "/M. Hummels.png" },
        { name: "G. Piqué", image: "/G. Piqué.png" },
        { name: "P. Pogba", image: "/P. Pogba.png" },
        { name: "G. Higuaín", image: "/G. Higuaín.png" },
        { name: "H. Lloris", image: "/H. Lloris.png" },
        { name: "S. Handanović", image: "/S. Handanović.png" },
        { name: "J. Rodríguez", image: "/J. Rodríguez.png" },
        { name: "C. Eriksen", image: "/C. Eriksen.png" },
        { name: "T. Silva", image: "/T. Silva.png" },
        { name: "M. Verratti", image: "/M. Verratti.png" },
        { name: "R. Lukaku", image: "/R. Lukaku.png" },
        { name: "P. Coutinho", image: "/P. Coutinho.png" },
        { name: "D. Mertens", image: "/D. Mertens.png" },
        { name: "L. Insigne", image: "/L. Insigne.png" },
        { name: "K. Benzema", image: "/K. Benzema.png" },
        { name: "I. Rakitić", image: "/I. Rakitić.png" },
        { name: "M. Pjanić", image: "/M. Pjanić.png" },
        { name: "D. Alaba", image: "/D. Alaba.png" },
        { name: "D. Silva", image: "/D. Silva.png" },
        { name: "R. Sterling", image: "/R. Sterling.png" },
        { name: "R. Firmino", image: "/R. Firmino.png" },
        { name: "T. Müller", image: "/T. Müller.png" },
        { name: "L. Bonucci", image: "/L. Bonucci.png" },
        { name: "T. Alderweireld", image: "/T. Alderweireld.png" },
        { name: "A. Sandro", image: "/A. Sandro.png" },
        { name: "D. Carvajal", image: "/D. Carvajal.png" },
        { name: "J. Kimmich", image: "/J. Kimmich.png" },
        { name: "B. Matuidi", image: "/B. Matuidi.png" },
        { name: "Fernandinho", image: "/Fernandinho.png" },
        { name: "A. Vidal", image: "/A. Vidal.png" },
        { name: "T. Alcântara", image: "/T. Alcântara.png" },
        { name: "C. Immobile", image: "/C. Immobile.png" },
        { name: "M. Icardi", image: "/M. Icardi.png" },
        { name: "P. Aubameyang", image: "/P. Aubameyang.png" },
        { name: "S. Mané", image: "/S. Mané.png" },
        { name: "A. Lacazette", image: "/A. Lacazette.png" },
        { name: "E. Džeko", image: "/E. Džeko.png" },
        { name: "Z. Ibrahimović", image: "/Z. Ibrahimović.png" },
        { name: "A. Iniesta", image: "/A. Iniesta.png" },
        { name: "M. Özil", image: "/M. Özil.png" },
        { name: "Á. Di María", image: "/Á. Di María.png" },
        { name: "R. Mahrez", image: "/R. Mahrez.png" },
        { name: "I. Perišić", image: "/I. Perišić.png" },
        { name: "D. Costa", image: "/D. Costa.png" },
        { name: "B. Silva", image: "/B. Silva.png" },
        { name: "T. Partey", image: "/T. Partey.png" },
        { name: "Fabinho", image: "/Fabinho.png" },
        { name: "Jorginho", image: "/Jorginho.png" },
        { name: "F. de Jong", image: "/F. de Jong.png" },
        { name: "M. de Ligt", image: "/M. de Ligt.png" },
        { name: "A. Laporte", image: "/A. Laporte.png" },
        { name: "K. Koulibaly", image: "/K. Koulibaly.png" },
        { name: "M. Škriniar", image: "/M. Škriniar.png" },
        { name: "Marquinhos", image: "/Marquinhos.png" },
        { name: "V. van Dijk", image: "/V. van Dijk.png" },
        { name: "R. Varane", image: "/R. Varane.png" },
        { name: "K. Manolas", image: "/K. Manolas.png" },
        { name: "N. Otamendi", image: "/N. Otamendi.png" },
        { name: "D. Alves", image: "/D. Alves.png" },
        { name: "C. Azpilicueta", image: "/C. Azpilicueta.png" }
    ];
export default playerImages;